name = "DCM"
uuid = "35ea0bf4-48dd-40f8-a693-405d0af369d8"
authors = ["ighdez <joseignaciohernandezh@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
Optim = "1.12.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
